version: '3.0'

services:
  api:
    build: ./
    restart: always
    ports:
    - 8080:8080
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: movierent
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
  db:
    image: postgres:9.6.16-alpine
    restart: always
    ports:
    - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql

